#!/bin/bash

#
# This file is managed by Rev Puppet service as described on Wiki
# page https://revwiki.atlassian.net/wiki/display/OP/Puppet+Centralized+Configuration+Management+System
# Please don't modify the file on the Puppet client server since your changes will be overwritten on the next
# Puppet agent run on the server.
#


if [ -f /var/log/nginx/error.log ]; then
	tail -F /var/log/nginx/error.log
else
	tail -f /var/log/apache2/error.log -F

fi
