#! /bin/sh -e
### BEGIN INIT INFO
# Provides:           revsw-modify-network-settings
# Required-Start:     $network
# Required-Stop:      $network
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Disable NIC Optimizations
# Description:        Disable NIC tx optimizations on HostVirtual servers
### END INIT INFO

#
# This file is managed by Rev Puppet service as described on Wiki
# page https://revwiki.atlassian.net/wiki/display/OP/Puppet+Centralized+Configuration+Management+System
# Please don't modify the file on the Puppet client server since your changes will be overwritten on the next
# Puppet agent run on the server.
#


set -e


if [ ! -z "`grep HostVirtual /etc/motd`" ]; then
	echo "Running on Host Virtual server - disabling NIC optimizations..."
	ethtool -K eth0 tx off
fi
